export default [
  ['StreamYard Getting Started', 'https://support.streamyard.com/hc/en-us/categories/201737543-Getting-Started', 'StreamYard', 'creation-setup', 'direct-domain', ['studio', 'guest', 'broadcast']],
  ['Riverside Studio Docs', 'https://docs.riverside.fm/', 'Riverside', 'creation-setup', 'direct-domain', ['record', 'edit', 'publish']],
  ['Mux Live Streaming Guide', 'https://docs.mux.com/guides/video/live-streaming', 'Mux', 'operator-control', 'direct-domain', ['ingest', 'playback', 'monitor']],
  ['Cloudflare Stream Docs', 'https://developers.cloudflare.com/stream/', 'Cloudflare Stream', 'operator-control', 'direct-domain', ['upload', 'live', 'playback']],
  ['AWS IVS User Guide', 'https://docs.aws.amazon.com/ivs/latest/UserGuide/what-is.html', 'Amazon IVS', 'operator-control', 'direct-domain', ['channel', 'stream', 'chat']],
  ['Vimeo Live Events Help', 'https://help.vimeo.com/hc/en-us/sections/115002897108-Live-Events', 'Vimeo', 'creation-setup', 'direct-domain', ['schedule', 'event', 'archive']],
  ['StreamElements Overlays', 'https://support.streamelements.com/hc/en-us/categories/115000789891-Overlays', 'StreamElements', 'creation-setup', 'direct-domain', ['overlay', 'alert', 'widget']],
  ['Owncast Self-Hosted Docs', 'https://owncast.online/docs/', 'Owncast', 'operator-control', 'adjacent-domain', ['install', 'configure', 'broadcast']],
  ['PeerTube Documentation', 'https://docs.joinpeertube.org/', 'PeerTube', 'operator-control', 'outside-domain', ['instance', 'publish', 'moderate']],
  ['Ant Media Server Docs', 'https://antmedia.io/docs/', 'Ant Media', 'operator-control', 'adjacent-domain', ['server', 'stream', 'scale']],
  ['TubeBuddy Help Center', 'https://www.tubebuddy.com/help/', 'TubeBuddy', 'library-launcher', 'adjacent-domain', ['tools', 'workflow', 'optimize']],
  ['vidIQ Creator Blog', 'https://vidiq.com/blog/category/youtube-tips/', 'vidIQ', 'library-launcher', 'adjacent-domain', ['research', 'optimize', 'publish']],
  ['Lightstream Studio Support', 'https://support.lightstreamstudio.com/hc/en-us', 'Lightstream', 'creation-setup', 'direct-domain', ['scene', 'guest', 'stream']],
  ['XSplit Broadcaster Support', 'https://support.xsplit.com/en/support/home', 'XSplit', 'creation-setup', 'direct-domain', ['source', 'layout', 'stream']],
  ['Ecamm Live Support', 'https://support.ecamm.com/', 'Ecamm', 'creation-setup', 'direct-domain', ['setup', 'show', 'record']],
  ['Restream Getting Started', 'https://support.restream.io/en/articles/3694369-getting-started', 'Restream', 'creation-setup', 'adjacent-domain', ['connect', 'multicast', 'monitor']],
  ['Cohost Platform Docs', 'https://www.cohost.cc/docs', 'Cohost', 'realtime-multiplayer', 'direct-domain', ['room', 'cohost', 'live']],
  ['Crowdcast Product Overview', 'https://www.crowdcast.io/product', 'Crowdcast', 'creation-setup', 'adjacent-domain', ['event', 'audience', 'replay']],
  ['LinkedIn Live Streaming Help', 'https://www.linkedin.com/help/linkedin/answer/a564446', 'LinkedIn', 'creation-setup', 'adjacent-domain', ['setup', 'go-live', 'analytics']],
  ['Facebook Live Producer Help', 'https://www.facebook.com/business/help/707679771080345', 'Facebook', 'creation-setup', 'adjacent-domain', ['producer', 'broadcast', 'insights']],
  ['Descript Recording Help', 'https://help.descript.com/hc/en-us/categories/115000776891-Recording', 'Descript', 'creation-setup', 'adjacent-domain', ['record', 'edit', 'share']],
  ['NDI Video Introduction', 'https://docs.ndi.video/docs/introduction/what-is-ndi', 'NDI', 'operator-control', 'outside-domain', ['source', 'network', 'sync']],
  ['OBS Optimized Settings', 'https://obsproject.com/kb/optimized-settings', 'OBS Studio', 'creation-setup', 'direct-domain', ['bitrate', 'encoder', 'test']],
  ['Elgato Stream Deck Plus Help', 'https://help.elgato.com/hc/en-us/articles/12492472727339-Stream-Deck-Plus', 'Elgato', 'operator-control', 'direct-domain', ['profile', 'action', 'stream']],
  ['Streamlabs Desktop Hub', 'https://streamlabs.com/content-hub/post/what-is-streamlabs-desktop', 'Streamlabs', 'library-launcher', 'direct-domain', ['install', 'scene', 'go-live']],
];
