export default [
['Railway Project Settings','https://docs.railway.app/guides/projects','Railway','operator-control','direct-domain',['project','env','deploy']],
['Render Dashboard Environments','https://render.com/docs/environment-variables','Render','admin-settings','direct-domain',['env','secrets','deploy']],
['Fly.io App Configuration','https://fly.io/docs/reference/configuration/','Fly.io','admin-settings','direct-domain',['config','regions','scaling']],
['DigitalOcean App Spec','https://docs.digitalocean.com/products/app-platform/reference/app-spec/','DigitalOcean','creation-setup','adjacent-domain',['spec','components','deploy']],
['Netlify Site Configuration','https://docs.netlify.com/site-deploys/overview/','Netlify','admin-settings','direct-domain',['build','deploy','domains']],
['Vercel Project Settings','https://vercel.com/docs/projects/project-configuration','Vercel','admin-settings','direct-domain',['project','env','domains']],
['Cloudflare Workers Config','https://developers.cloudflare.com/workers/configuration/','Cloudflare','operator-control','direct-domain',['bindings','routes','vars']],
['Heroku Config Vars','https://devcenter.heroku.com/articles/config-vars','Heroku','admin-settings','adjacent-domain',['config','addons','deploy']],
['Supabase Database Settings','https://supabase.com/docs/guides/database/overview','Supabase','admin-settings','direct-domain',['database','rls','migrations']],
['PlanetScale Branching','https://planetscale.com/docs/concepts/branching','PlanetScale','operator-control','adjacent-domain',['branch','schema','deploy']],
['Neon Project Settings','https://neon.tech/docs/manage/projects','Neon','admin-settings','adjacent-domain',['project','branch','compute']],
['Turso Database CLI','https://docs.turso.tech/reference/introduction','Turso','operator-control','outside-domain',['database','replication','cli']],
['Upstash Redis Console','https://upstash.com/docs/redis/overall/getstarted','Upstash','admin-settings','adjacent-domain',['database','keys','billing']],
['Sentry Project Settings','https://docs.sentry.io/product/projects/','Sentry','admin-settings','direct-domain',['issues','alerts','integrations']],
['Datadog Dashboards','https://docs.datadoghq.com/dashboards/','Datadog','operator-control','adjacent-domain',['dashboard','metrics','alerts']],
['Grafana Cloud Dashboards','https://grafana.com/docs/grafana-cloud/visualizations/dashboards/','Grafana','operator-control','adjacent-domain',['dashboard','panels','alerts']],
['PagerDuty Services','https://support.pagerduty.com/docs/services','PagerDuty','admin-settings','adjacent-domain',['service','escalation','oncall']],
['Atlassian Statuspage','https://support.atlassian.com/statuspage/docs/what-is-statuspage/','Statuspage','public-home','adjacent-domain',['incident','components','subscribe']],
['Better Stack Uptime','https://betterstack.com/docs/uptime/','Better Stack','operator-control','outside-domain',['monitor','incident','status']],
['UptimeRobot Dashboard','https://uptimerobot.com/api/','UptimeRobot','operator-control','outside-domain',['monitor','alert','report']],
['Pulumi Console','https://www.pulumi.com/docs/pulumi-cloud/','Pulumi','admin-settings','outside-domain',['stack','deploy','policy']],
['Terraform Registry Modules','https://developer.hashicorp.com/terraform/registry','Terraform','library-launcher','evidence-craft',['module','provider','version']],
['Docker Hub Repositories','https://docs.docker.com/docker-hub/repos/','Docker Hub','library-launcher','adjacent-domain',['repo','tags','settings']],
['Kubernetes Dashboard','https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/','Kubernetes','operator-control','outside-domain',['cluster','workload','logs']],
['GitHub Actions Workflow','https://docs.github.com/en/actions/using-workflows','GitHub Actions','creation-setup','direct-domain',['workflow','jobs','secrets']],
];
