export default [
['Gumroad Product Setup','https://help.gumroad.com/article/149-products','Gumroad','creation-setup','direct-domain',['product','pricing','publish']],
['Lemon Squeezy Store','https://docs.lemonsqueezy.com/help/products','Lemon Squeezy','creation-setup','adjacent-domain',['product','checkout','license']],
['Paddle Vendor Dashboard','https://developer.paddle.com/build/onboarding/overview','Paddle','admin-settings','adjacent-domain',['catalog','checkout','tax']],
['Chargebee Product Catalog','https://www.chargebee.com/docs/2.0/product-catalog.html','Chargebee','creation-setup','adjacent-domain',['plan','addon','coupon']],
['Recurly Plans','https://docs.recurly.com/docs/plans','Recurly','creation-setup','outside-domain',['plan','subscription','dunning']],
['Buy Me a Coffee Page','https://help.buymeacoffee.com/en/articles/6970887-how-to-set-up-your-page','Buy Me a Coffee','creation-setup','outside-domain',['page','goal','membership']],
['Memberful Membership','https://memberful.com/help/setup/','Memberful','creation-setup','adjacent-domain',['plan','member','content']],
['Ghost Members Portal','https://ghost.org/help/members/','Ghost','commerce-checkout','adjacent-domain',['member','tier','portal']],
['Substack Creator Settings','https://support.substack.com/hc/en-us/articles/360041349112','Substack','admin-settings','adjacent-domain',['publication','paywall','email']],
['Teachable Course Creation','https://support.teachable.com/hc/en-us/articles/115000083131','Teachable','creation-setup','adjacent-domain',['course','pricing','students']],
['Thinkific Course Builder','https://support.thinkific.com/hc/en-us/articles/206353098','Thinkific','creation-setup','outside-domain',['course','market','sales']],
['Kajabi Products','https://help.kajabi.com/hc/en-us/articles/360015995031','Kajabi','creation-setup','outside-domain',['product','pipeline','checkout']],
['Etsy Shop Manager','https://help.etsy.com/hc/en-us/articles/360000333874','Etsy','operator-control','adjacent-domain',['listing','orders','stats']],
['Shopify Partners Dashboard','https://help.shopify.com/en/partners/dashboard','Shopify Partners','operator-control','direct-domain',['store','app','payouts']],
['Amazon Seller Central Help','https://sellercentral.amazon.com/gp/help/external/G200333160','Amazon Seller','operator-control','outside-domain',['listing','inventory','orders']],
['eBay Seller Hub','https://www.ebay.com/help/selling/listings/creating-managing-listings','eBay','operator-control','outside-domain',['listing','shipping','returns']],
['WooCommerce Documentation','https://woocommerce.com/documentation/woocommerce/','WooCommerce','creation-setup','adjacent-domain',['product','checkout','shipping']],
['BigCommerce Control Panel','https://support.bigcommerce.com/s/article/Catalog-Overview','BigCommerce','operator-control','adjacent-domain',['catalog','orders','channels']],
['Squarespace Commerce','https://support.squarespace.com/hc/en-us/articles/206543167','Squarespace','commerce-checkout','adjacent-domain',['product','checkout','tax']],
['Wix Stores Setup','https://support.wix.com/en/article/wix-stores-creating-a-product','Wix','creation-setup','outside-domain',['product','cart','payments']],
['Podia Digital Products','https://help.podia.com/en/articles/3834190','Podia','creation-setup','outside-domain',['product','checkout','email']],
['ConvertKit Commerce','https://help.kit.com/en/articles/4199329','ConvertKit','commerce-checkout','adjacent-domain',['product','checkout','subscribers']],
['Mighty Networks Community','https://support.mn.co/hc/en-us/articles/360016110451','Mighty Networks','authenticated-home','outside-domain',['community','space','membership']],
['Circle Community Spaces','https://help.circle.so/c/circle-basics','Circle','authenticated-home','adjacent-domain',['space','member','events']],
['Discourse Admin Guide','https://meta.discourse.org/t/discourse-admin-quick-start-guide/93648','Discourse','admin-settings','outside-domain',['category','user','moderation']],
];
