export default [
  ['Auth0 Universal Login Docs','https://auth0.com/docs/authenticate/login/auth0-universal-login','Auth0','auth-onboarding','adjacent-domain',['login','signup','social'],'guideline'],
  ['Okta Developer Sign-In','https://developer.okta.com/docs/guides/sign-in-to-spa-embedded-widget/main/','Okta','auth-onboarding','adjacent-domain',['widget','redirect','mfa'],'guideline'],
  ['WorkOS SSO Docs','https://workos.com/docs/sso','WorkOS','auth-onboarding','adjacent-domain',['sso','directory','connection'],'guideline'],
  ['Clerk Components Docs','https://clerk.com/docs/components/overview','Clerk','auth-onboarding','adjacent-domain',['components','sign-in','user-button'],'guideline'],
  ['Keycloak Server Admin','https://www.keycloak.org/docs/latest/server_admin/','Keycloak','admin-settings','outside-domain',['realm','clients','roles'],'guideline'],
  ['AWS Cognito User Pools','https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html','AWS Cognito','auth-onboarding','outside-domain',['user-pool','attributes','mfa'],'guideline'],
  ['Stytch Consumer Auth','https://stytch.com/docs/guides/consumer-auth/overview','Stytch','auth-onboarding','adjacent-domain',['magic-link','oauth','session'],'guideline'],
  ['FusionAuth Login API','https://fusionauth.io/docs/v1/tech/apis/login','FusionAuth','auth-onboarding','outside-domain',['login','refresh','logout'],'guideline'],
  ['Microsoft Entra ID Docs','https://learn.microsoft.com/en-us/entra/identity/','Microsoft Entra','auth-onboarding','outside-domain',['tenant','app-reg','conditional'],'guideline'],
  ['Google Identity Platform','https://cloud.google.com/identity-platform/docs','Google Identity','auth-onboarding','outside-domain',['providers','mfa','blocking'],'guideline'],
  ['GitHub OAuth Apps Docs','https://docs.github.com/en/apps/oauth-apps/building-oauth-apps','GitHub','auth-onboarding','direct-domain',['oauth-app','scopes','callback'],'guideline'],
  ['Discord OAuth2 Guide','https://discord.com/developers/docs/topics/oauth2','Discord','auth-onboarding','direct-domain',['oauth2','scopes','token'],'guideline'],
  ['Twitch Authentication Guide','https://dev.twitch.tv/docs/authentication/','Twitch','auth-onboarding','direct-domain',['oauth','tokens','scopes'],'guideline'],
  ['Spotify Authorization Guide','https://developer.spotify.com/documentation/web-api/tutorials/code-flow','Spotify','auth-onboarding','adjacent-domain',['code-flow','scopes','refresh'],'guideline'],
  ['LinkedIn OAuth Docs','https://learn.microsoft.com/en-us/linkedin/shared/authentication/authentication','LinkedIn','auth-onboarding','adjacent-domain',['oauth','permissions','tokens'],'guideline'],
  ['Canva Connect API Auth','https://www.canva.dev/docs/connect/authentication/','Canva','auth-onboarding','adjacent-domain',['oauth','scopes','tokens'],'guideline'],
  ['Dropbox OAuth Guide','https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize','Dropbox','auth-onboarding','adjacent-domain',['oauth','pkce','refresh'],'guideline'],
  ['Box OAuth2 Docs','https://developer.box.com/guides/authentication/oauth2/','Box','auth-onboarding','adjacent-domain',['oauth2','consent','token'],'guideline'],
  ['Slack OAuth Scopes','https://api.slack.com/authentication/oauth-v2','Slack','auth-onboarding','adjacent-domain',['oauth','scopes','install'],'guideline'],
  ['Notion Authorization','https://developers.notion.com/docs/authorization','Notion','auth-onboarding','adjacent-domain',['oauth','integration','token'],'guideline'],
  ['Zoom OAuth Docs','https://developers.zoom.us/docs/integrations/oauth/','Zoom','auth-onboarding','adjacent-domain',['oauth','scopes','token'],'guideline'],
  ['Twilio Verify API','https://www.twilio.com/docs/verify/api','Twilio','auth-onboarding','adjacent-domain',['verify','sms','totp'],'guideline'],
  ['1Password SSO Connect','https://developer.1password.com/docs/sso-connect/','1Password','auth-onboarding','adjacent-domain',['sso','connect','session'],'guideline'],
  ['Duo Admin Guide','https://duo.com/docs/administration','Duo','admin-settings','outside-domain',['admin','policies','users'],'guideline'],
  ['Ping Identity SSO','https://docs.pingidentity.com/','Ping Identity','auth-onboarding','outside-domain',['sso','federation','mfa'],'guideline'],
];
