export default [
  ['iOS Shortcuts User Guide','https://support.apple.com/guide/shortcuts/welcome/ios','Apple Shortcuts','mobile-responsive','evidence-craft','native-mobile',['shortcut','automation','share'],'guideline'],
  ['iOS Control Center','https://support.apple.com/en-us/HT202093','Apple iOS','mobile-responsive','evidence-craft','native-mobile',['control-center','toggle','customize'],'guideline'],
  ['iOS Widgets Home Screen','https://support.apple.com/en-us/HT207122','Apple Widgets','mobile-responsive','evidence-craft','native-mobile',['widget','home-screen','stack'],'guideline'],
  ['iOS Focus Modes','https://support.apple.com/en-us/HT212608','Apple Focus','mobile-responsive','evidence-craft','native-mobile',['focus','schedule','filter'],'guideline'],
  ['iOS Live Activities','https://developer.apple.com/documentation/activitykit/displaying-live-data-with-live-activities','Apple Live Activities','realtime-multiplayer','direct-domain','native-mobile',['live-activity','lock-screen','update'],'guideline'],
  ['Sign in with Apple HIG','https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple','Apple HIG','auth-onboarding','evidence-craft','native-mobile',['sign-in','button','privacy'],'guideline'],
  ['SF Symbols App','https://developer.apple.com/sf-symbols/','Apple SF Symbols','design-system-craft','evidence-craft','native-mobile',['symbols','weight','render'],'guideline'],
  ['TestFlight Beta Testing','https://developer.apple.com/testflight/','Apple TestFlight','creation-setup','direct-domain','native-mobile',['beta','invite','feedback'],'guideline'],
  ['iOS Push Notifications','https://developer.apple.com/documentation/usernotifications','Apple Push','operator-control','direct-domain','native-mobile',['push','permission','payload'],'guideline'],
  ['SwiftUI Tutorials','https://developer.apple.com/tutorials/swiftui','Apple SwiftUI','design-system-craft','evidence-craft','native-mobile',['swiftui','layout','state'],'guideline'],
  ['UIKit App Architecture','https://developer.apple.com/documentation/uikit','Apple UIKit','design-system-craft','evidence-craft','native-mobile',['uikit','view-controller','lifecycle'],'guideline'],
  ['Wallet Pass Design','https://developer.apple.com/wallet/get-started/','Apple Wallet','commerce-checkout','adjacent-domain','native-mobile',['pass','barcode','update'],'guideline'],
  ['MapKit JS Overview','https://developer.apple.com/maps/web/','Apple MapKit','library-launcher','direct-domain','native-mobile',['map','annotation','search'],'guideline'],
  ['HealthKit Overview','https://developer.apple.com/documentation/healthkit','Apple HealthKit','operator-control','direct-domain','native-mobile',['health','permission','sample'],'guideline'],
  ['HomeKit Accessory Setup','https://developer.apple.com/homekit/','Apple HomeKit','creation-setup','direct-domain','native-mobile',['accessory','pair','room'],'guideline'],
  ['SiriKit Intents','https://developer.apple.com/documentation/sirikit','Apple SiriKit','creation-setup','direct-domain','native-mobile',['intent','shortcut','response'],'guideline'],
  ['Game Center Guide','https://developer.apple.com/game-center/','Apple Game Center','realtime-multiplayer','direct-domain','native-mobile',['leaderboard','achievement','match'],'guideline'],
  ['StoreKit In-App Purchase','https://developer.apple.com/storekit/','Apple StoreKit','commerce-checkout','direct-domain','native-mobile',['iap','subscription','restore'],'guideline'],
  ['ARKit Overview','https://developer.apple.com/augmented-reality/arkit/','Apple ARKit','editorial-experimental','direct-domain','native-mobile',['ar','anchor','session'],'guideline'],
  ['TipKit Framework','https://developer.apple.com/documentation/tipkit','Apple TipKit','library-launcher','direct-domain','native-mobile',['tip','popover','rules'],'guideline'],
  ['SharePlay Developer','https://developer.apple.com/shareplay/','Apple SharePlay','realtime-multiplayer','direct-domain','native-mobile',['shareplay','group','sync'],'guideline'],
  ['Telegram iOS FAQ','https://telegram.org/faq#q-what-is-telegram','Telegram','authenticated-home','adjacent-domain','native-mobile',['chat','sync','privacy'],'guideline'],
  ['Signal Support iOS','https://support.signal.org/hc/en-us/categories/360001344992','Signal','authenticated-home','adjacent-domain','native-mobile',['message','call','privacy'],'guideline'],
  ['WhatsApp iPhone Help','https://faq.whatsapp.com/iphone','WhatsApp','authenticated-home','adjacent-domain','native-mobile',['chat','call','status'],'guideline'],
  ['iOS App Clips','https://developer.apple.com/app-clips/','Apple App Clips','auth-onboarding','direct-domain','native-mobile',['app-clip','nfc','invoke'],'guideline'],
];
