export default [
  ['Android Notifications Help','https://support.google.com/android/answer/9079661','Android','mobile-responsive','evidence-craft','native-mobile',['channels','importance','dnd'],'guideline'],
  ['Android Widgets Guide','https://developer.android.com/develop/ui/views/appwidgets','Android','mobile-responsive','evidence-craft','native-mobile',['sizes','placement','updates'],'guideline'],
  ['Material 3 Components','https://m3.material.io/components','Material','design-system-craft','evidence-craft','native-mobile',['buttons','navigation','sheets'],'design-system'],
  ['Jetpack Compose Layout','https://developer.android.com/jetpack/compose/layout','Android','mobile-responsive','evidence-craft','native-mobile',['layout','modifiers','scroll'],'guideline'],
  ['Android Navigation Component','https://developer.android.com/guide/navigation','Android','mobile-responsive','evidence-craft','native-mobile',['graph','destinations','back'],'guideline'],
  ['Android Permissions Overview','https://developer.android.com/guide/topics/permissions/overview','Android','mobile-responsive','evidence-craft','native-mobile',['runtime','settings','rationale'],'guideline'],
  ['Android Backup Restore','https://developer.android.com/identity/data/backup','Android','mobile-responsive','evidence-craft','native-mobile',['backup','restore','transfer'],'guideline'],
  ['Android 14 Features','https://developer.android.com/about/versions/14/features','Android','mobile-responsive','evidence-craft','native-mobile',['features','privacy','media'],'guideline'],
  ['Android TV Design','https://developer.android.com/design/ui/tv','Android TV','mobile-responsive','evidence-craft','native-mobile',['leanback','focus','d-pad'],'guideline'],
  ['Wear OS Tiles','https://developer.android.com/training/wearables/tiles','Wear OS','mobile-responsive','evidence-craft','native-mobile',['tiles','complications','sync'],'guideline'],
  ['Android Auto App Design','https://developer.android.com/training/cars/apps','Android Auto','mobile-responsive','evidence-craft','native-mobile',['templates','limits','driver'],'guideline'],
  ['Android Enterprise Work Profile','https://support.google.com/work/android/answer/6191949','Android Enterprise','admin-settings','evidence-craft','native-mobile',['work-profile','policies','apps'],'guideline'],
  ['Google Play Console Help','https://support.google.com/googleplay/android-developer','Play Console','admin-settings','direct-domain','native-mobile',['dashboard','releases','policy'],'flow'],
  ['Samsung One UI Tips','https://www.samsung.com/us/support/answer/ANS00087645/','Samsung','mobile-responsive','outside-domain','native-mobile',['gestures','panels','settings'],'flow'],
  ['Discord Android Voice','https://support.discord.com/hc/en-us/articles/13167125824151','Discord','realtime-multiplayer','adjacent-domain','native-mobile',['voice','permissions','push'],'flow'],
  ['Twitch Android Broadcasting','https://help.twitch.tv/s/article/broadcasting-from-your-mobile-device','Twitch','creation-setup','direct-domain','native-mobile',['go-live','chat','quality'],'flow'],
  ['YouTube Android Live','https://support.google.com/youtube/answer/2474026','YouTube','creation-setup','direct-domain','native-mobile',['mobile-live','chat','visibility'],'flow'],
  ['Instagram Android Reels Live','https://help.instagram.com/1631228644201995','Instagram','creation-setup','adjacent-domain','native-mobile',['live','comments','moderation'],'flow'],
  ['Reddit Android Mod Tools','https://support.reddithelp.com/hc/en-us/articles/360043066031','Reddit','admin-settings','adjacent-domain','native-mobile',['mod-queue','reports','settings'],'flow'],
  ['Spotify Android Car Mode','https://support.spotify.com/us/article/car-mode/','Spotify','mobile-responsive','adjacent-domain','native-mobile',['car','controls','queue'],'flow'],
  ['Slack Android Notifications','https://slack.com/help/articles/201355156','Slack','admin-settings','adjacent-domain','native-mobile',['notifications','badges','snooze'],'flow'],
  ['Zoom Android Meetings','https://support.zoom.us/hc/en-us/articles/201362603','Zoom','realtime-multiplayer','adjacent-domain','native-mobile',['join','host','controls'],'flow'],
  ['Google Maps Android Navigation','https://support.google.com/maps/answer/3273406','Google Maps','mobile-responsive','outside-domain','native-mobile',['navigation','voice','layers'],'flow'],
  ['Chrome Android Tabs Groups','https://support.google.com/chrome/answer/2391819','Chrome','library-launcher','outside-domain','native-mobile',['tabs','groups','sync'],'flow'],
  ['Telegram Android Secret Chat','https://telegram.org/faq#secret-chats','Telegram','realtime-multiplayer','outside-domain','native-mobile',['secret','timer','keys'],'flow'],
];
