export default [
  ['NN Group UX Articles','https://www.nngroup.com/articles/','NN Group','design-system-craft','evidence-craft','web-responsive',['article-index','topic-filter','detail'],'case-study'],
  ['Baymard Checkout Research','https://baymard.com/research/checkout-usability','Baymard','commerce-checkout','evidence-craft','web-responsive',['research','benchmark','detail'],'case-study'],
  ['Laws of UX','https://lawsofux.com/','Laws of UX','design-system-craft','evidence-craft','web-responsive',['principles','cards','detail'],'guideline'],
  ['GoodUI Patterns','https://goodui.org/','GoodUI','design-system-craft','evidence-craft','web-responsive',['patterns','evidence','detail'],'case-study'],
  ['UX Collective Articles','https://uxdesign.cc/','UX Collective','editorial-experimental','evidence-craft','web-responsive',['feed','article','tags'],'case-study'],
  ['Smashing Magazine UX','https://www.smashingmagazine.com/category/ux-design/','Smashing','design-system-craft','evidence-craft','web-responsive',['category','article','resources'],'case-study'],
  ['A List Apart UX','https://alistapart.com/','A List Apart','editorial-experimental','evidence-craft','web-responsive',['articles','topics','archive'],'case-study'],
  ['Material Design Motion','https://m3.material.io/styles/motion/overview','Material','design-system-craft','evidence-craft','web-responsive',['overview','easing','transitions'],'guideline'],
  ['Carbon Motion Guidelines','https://carbondesignsystem.com/guidelines/motion/overview/','Carbon','design-system-craft','evidence-craft','web-responsive',['overview','duration','curves'],'guideline'],
  ['Fluent UI Motion','https://fluent2.microsoft.design/motion','Fluent','design-system-craft','evidence-craft','web-responsive',['principles','patterns','timing'],'guideline'],
  ['Atlassian Design Principles','https://atlassian.design/foundations/content-design/principles','Atlassian','design-system-craft','evidence-craft','web-responsive',['principles','voice','examples'],'guideline'],
  ['IBM Accessibility Checklist','https://www.ibm.com/design/accessibility/checklist/','IBM','design-system-craft','evidence-craft','web-responsive',['checklist','criteria','examples'],'guideline'],
  ['W3C WCAG Overview','https://www.w3.org/WAI/standards-guidelines/wcag/','W3C','design-system-craft','evidence-craft','web-responsive',['levels','principles','techniques'],'guideline'],
  ['Refactoring UI Tips','https://www.refactoringui.com/','Refactoring UI','design-system-craft','evidence-craft','web-responsive',['tips','examples','purchase'],'case-study'],
  ['Practical Typography Summary','https://practicaltypography.com/summary-of-key-rules.html','Practical Typography','design-system-craft','evidence-craft','web-responsive',['rules','examples','detail'],'guideline'],
  ['Checklist Design Patterns','https://www.checklist.design/','Checklist Design','library-launcher','evidence-craft','web-responsive',['patterns','checklist','detail'],'case-study'],
  ['Page Flows Library','https://pageflows.com/','Page Flows','library-launcher','evidence-craft','web-responsive',['flows','product','screens'],'case-study'],
  ['Built for Mars UX','https://builtformars.com/','Built for Mars','editorial-experimental','evidence-craft','web-responsive',['cases','analysis','patterns'],'case-study'],
  ['UX Bites Micro Patterns','https://www.uxbites.com/','UX Bites','library-launcher','evidence-craft','web-responsive',['bites','pattern','detail'],'case-study'],
  ['Design Spells Interactions','https://designspells.com/','Design Spells','editorial-experimental','evidence-craft','web-responsive',['spells','detail','tags'],'case-study'],
  ['WCAG Understanding Docs','https://www.w3.org/WAI/WCAG21/Understanding/','W3C','design-system-craft','evidence-craft','web-responsive',['understanding','criteria','examples'],'guideline'],
  ['A11y Project Checklist','https://www.a11yproject.com/checklist/','A11y Project','design-system-craft','evidence-craft','web-responsive',['checklist','items','resources'],'guideline'],
  ['Growth Design Cases','https://growth.design/case-studies','Growth Design','editorial-experimental','evidence-craft','web-responsive',['cases','story','takeaways'],'case-study'],
  ['Mobbin Alternatives UX Archive','https://uxarchive.com/','UX Archive','library-launcher','evidence-craft','web-responsive',['flows','app','screens'],'case-study'],
  ['UI Patterns Catalog','https://ui-patterns.com/patterns','UI Patterns','library-launcher','evidence-craft','web-responsive',['pattern','examples','detail'],'case-study'],
];
