export default [
  ['Webflow University','https://university.webflow.com/','Webflow','library-launcher','outside-domain','web-responsive',['courses','lessons','projects'],'flow'],
  ['Webflow Showcase','https://webflow.com/made-in-webflow','Webflow','editorial-experimental','outside-domain','web-responsive',['showcase','filter','detail'],'flow'],
  ['Squarespace Templates','https://www.squarespace.com/templates','Squarespace','library-launcher','outside-domain','web-responsive',['templates','preview','start'],'flow'],
  ['Wix Studio Templates','https://www.wix.com/studio/templates','Wix','library-launcher','outside-domain','web-responsive',['templates','categories','preview'],'flow'],
  ['Framer Updates Blog','https://www.framer.com/updates/','Framer','editorial-experimental','outside-domain','web-responsive',['updates','features','changelog'],'flow'],
  ['Readymag Examples','https://readymag.com/examples/','Readymag','editorial-experimental','outside-domain','web-responsive',['examples','scroll','detail'],'flow'],
  ['Spline 3D Product Page','https://spline.design/','Spline','editorial-experimental','outside-domain','web-responsive',['hero','3d','features'],'flow'],
  ['Rive Features Page','https://rive.app/features','Rive','editorial-experimental','outside-domain','web-responsive',['features','runtime','examples'],'flow'],
  ['LottieFiles Marketplace','https://lottiefiles.com/marketplace','LottieFiles','library-launcher','outside-domain','web-responsive',['marketplace','preview','download'],'flow'],
  ['Dora AI Site Builder','https://www.dora.run/','Dora','editorial-experimental','outside-domain','web-responsive',['hero','3d','templates'],'flow'],
  ['Adobe Creative Cloud Plans','https://www.adobe.com/creativecloud/plans.html','Adobe','commerce-checkout','outside-domain','web-responsive',['plans','compare','trial'],'flow'],
  ['Sketch App Features','https://www.sketch.com/features/','Sketch','editorial-experimental','outside-domain','web-responsive',['features','collab','plugins'],'flow'],
  ['InVision Freehand','https://www.invisionapp.com/freehand','InVision','creation-setup','outside-domain','web-responsive',['canvas','collab','share'],'flow'],
  ['Marvel App Prototyping','https://marvelapp.com/prototyping/','Marvel','creation-setup','outside-domain','web-responsive',['prototype','screens','share'],'flow'],
  ['ProtoPie Learn','https://www.protopie.io/learn','ProtoPie','library-launcher','outside-domain','web-responsive',['learn','tutorials','examples'],'flow'],
  ['Principle for Mac','https://principleformac.com/','Principle','editorial-experimental','outside-domain','web-responsive',['features','demo','download'],'flow'],
  ['Origami Studio Learn','https://origami.design/documentation/','Origami','library-launcher','outside-domain','web-responsive',['docs','components','export'],'flow'],
  ['Penpot Help Center','https://help.penpot.app/','Penpot','library-launcher','outside-domain','web-responsive',['help','workspace','export'],'flow'],
  ['Lunacy Documentation','https://docs.icons8.com/lunacy/','Lunacy','library-launcher','outside-domain','web-responsive',['docs','components','export'],'flow'],
  ['Zeplin Getting Started','https://support.zeplin.io/en/articles/252752-getting-started','Zeplin','creation-setup','outside-domain','web-responsive',['setup','projects','handoff'],'flow'],
  ['Abstract Help','https://help.goabstract.com/hc/en-us','Abstract','admin-settings','outside-domain','web-responsive',['help','version','review'],'flow'],
  ['Maze Research Guide','https://maze.co/guides/ux-research/','Maze','library-launcher','evidence-craft','web-responsive',['guide','methods','templates'],'flow'],
  ['Hotjar Guides','https://www.hotjar.com/guides/','Hotjar','library-launcher','evidence-craft','web-responsive',['guides','heatmaps','feedback'],'flow'],
  ['FullStory Learning Center','https://learn.fullstory.com/','FullStory','library-launcher','evidence-craft','web-responsive',['learn','analytics','sessions'],'flow'],
  ['Carrd Documentation','https://carrd.co/docs','Carrd','creation-setup','outside-domain','web-responsive',['docs','sites','publish'],'flow'],
];
