export default [
  ['NN/g Group Heuristic Evaluation', 'https://www.nngroup.com/articles/how-to-conduct-a-heuristic-evaluation/', 'NN Group', 'design-system-craft', 'evidence-craft', ['heuristics', 'evaluation', 'checklist'], 'guideline'],
  ['Baymard Mobile Checkout', 'https://baymard.com/blog/mobile-checkout-usability', 'Baymard', 'design-system-craft', 'evidence-craft', ['mobile', 'checkout', 'patterns'], 'case-study'],
  ['Growth.Design Psychology', 'https://growth.design/psychology', 'Growth.Design', 'design-system-craft', 'evidence-craft', ['psychology', 'patterns', 'comic'], 'case-study'],
  ['Mobbin Flow Patterns', 'https://mobbin.com/glossary', 'Mobbin', 'library-launcher', 'evidence-craft', ['glossary', 'patterns', 'mobile'], 'design-system'],
  ['PatternTap Mobile UI', 'https://pttrns.com/', 'PatternTap', 'library-launcher', 'evidence-craft', ['pattern-grid', 'screenshot', 'detail'], 'design-system'],
  ['Material 3 Foundations', 'https://m3.material.io/foundations', 'Material Design', 'design-system-craft', 'evidence-craft', ['color', 'typography', 'layout'], 'design-system'],
  ['Carbon Components React', 'https://carbondesignsystem.com/components/overview/', 'IBM Carbon', 'design-system-craft', 'evidence-craft', ['components', 'overview', 'usage'], 'design-system'],
  ['Atlassian Design Tokens', 'https://atlassian.design/foundations/tokens', 'Atlassian', 'design-system-craft', 'evidence-craft', ['tokens', 'semantic', 'scale'], 'design-system'],
  ['Primer Color Foundations', 'https://primer.style/foundations/color', 'GitHub Primer', 'design-system-craft', 'evidence-craft', ['tokens', 'contrast', 'usage'], 'design-system'],
  ['Ant Design Components', 'https://ant.design/components/overview', 'Ant Design', 'design-system-craft', 'evidence-craft', ['components', 'overview', 'usage'], 'design-system'],
  ['Chakra UI Theming', 'https://chakra-ui.com/docs/styled-system/customize-theme', 'Chakra UI', 'design-system-craft', 'evidence-craft', ['theme', 'tokens', 'semantic'], 'design-system'],
  ['Radix Primitives Overview', 'https://www.radix-ui.com/primitives/docs/overview/introduction', 'Radix UI', 'design-system-craft', 'evidence-craft', ['primitives', 'a11y', 'unstyled'], 'design-system'],
  ['shadcn/ui Components', 'https://ui.shadcn.com/docs/components', 'shadcn/ui', 'design-system-craft', 'evidence-craft', ['components', 'copy-paste', 'tailwind'], 'design-system'],
  ['Storybook Docs Addon', 'https://storybook.js.org/docs/writing-docs/introduction', 'Storybook', 'design-system-craft', 'evidence-craft', ['docs', 'stories', 'mdx'], 'guideline'],
  ['Zeroheight Styleguide', 'https://help.zeroheight.com/hc/en-us', 'Zeroheight', 'library-launcher', 'evidence-craft', ['styleguide', 'publish', 'sync'], 'flow'],
  ['Supernova Design Tokens', 'https://learn.supernova.io/latest/design-systems/design-tokens', 'Supernova', 'design-system-craft', 'evidence-craft', ['tokens', 'pipeline', 'export'], 'guideline'],
  ['Tokens Studio Figma', 'https://docs.tokens.studio/', 'Tokens Studio', 'creation-setup', 'evidence-craft', ['tokens', 'figma', 'sync'], 'guideline'],
  ['Style Dictionary Docs', 'https://amzn.github.io/style-dictionary/', 'Style Dictionary', 'design-system-craft', 'evidence-craft', ['tokens', 'build', 'platforms'], 'guideline'],
  ['Inclusive Components', 'https://inclusive-components.design/', 'Inclusive Components', 'design-system-craft', 'evidence-craft', ['a11y', 'patterns', 'components'], 'guideline'],
  ['Deque Web Checklist', 'https://dequeuniversity.com/checklists/web/', 'Deque', 'design-system-craft', 'evidence-craft', ['checklist', 'criteria', 'examples'], 'guideline'],
  ['Deque axe Rules', 'https://dequeuniversity.com/rules/axe/', 'Deque', 'design-system-craft', 'evidence-craft', ['rules', 'automation', 'wcag'], 'guideline'],
  ['WAI-ARIA Authoring Practices', 'https://www.w3.org/WAI/ARIA/apg/', 'W3C', 'design-system-craft', 'evidence-craft', ['patterns', 'widgets', 'keyboard'], 'guideline'],
  ['Microsoft Fluent 2', 'https://fluent2.microsoft.design/', 'Microsoft Fluent', 'design-system-craft', 'evidence-craft', ['fluent2', 'components', 'motion'], 'design-system'],
  ['Salesforce Lightning Design', 'https://www.lightningdesignsystem.com/', 'Salesforce', 'design-system-craft', 'evidence-craft', ['components', 'tokens', 'patterns'], 'design-system'],
  ['GitLab Pajamas Design System', 'https://design.gitlab.com/', 'GitLab', 'design-system-craft', 'evidence-craft', ['components', 'guidelines', 'tokens'], 'design-system'],
];
