export default [
  ['Nielsen Norman Articles', 'https://www.nngroup.com/articles/', 'NN Group Articles', 'design-system-craft', 'evidence-craft', ['article-index', 'topic-filter', 'read']],
  ['IDEO Design Thinking', 'https://designthinking.ideo.com/', 'IDEO DT', 'design-system-craft', 'evidence-craft', ['methods', 'tools', 'stories']],
  ['d.school Resources', 'https://dschool.stanford.edu/resources', 'd.school', 'design-system-craft', 'evidence-craft', ['toolkit', 'guides', 'videos']],
  ['Figma Best Practices', 'https://www.figma.com/best-practices/', 'Figma BP', 'design-system-craft', 'evidence-craft', ['design-systems', 'handoff', 'files']],
  ['Amplitude Product Analytics', 'https://help.amplitude.com/hc/en-us', 'Amplitude', 'design-system-craft', 'evidence-craft', ['events', 'funnels', 'cohorts']],
  ['Mixpanel Docs', 'https://docs.mixpanel.com/', 'Mixpanel', 'design-system-craft', 'evidence-craft', ['tracking', 'reports', 'integrations']],
  ['PostHog Docs', 'https://posthog.com/docs', 'PostHog', 'design-system-craft', 'evidence-craft', ['product-analytics', 'feature-flags', 'session-replay']],
  ['Segment Connections', 'https://segment.com/docs/connections/', 'Segment', 'design-system-craft', 'evidence-craft', ['sources', 'destinations', 'warehouses']],
  ['Heap Analytics Guide', 'https://help.heap.io/', 'Heap', 'design-system-craft', 'evidence-craft', ['autocapture', 'events', 'insights']],
  ['FullStory Knowledge Base', 'https://help.fullstory.com/hc/en-us', 'FullStory', 'design-system-craft', 'evidence-craft', ['session-replay', 'search', 'metrics']],
  ['Hotjar Help', 'https://help.hotjar.com/hc/en-us', 'Hotjar', 'design-system-craft', 'evidence-craft', ['heatmaps', 'recordings', 'surveys']],
  ['Optimizely Knowledge', 'https://support.optimizely.com/hc/en-us', 'Optimizely', 'design-system-craft', 'evidence-craft', ['experiments', 'personalization', 'results']],
  ['VWO Knowledge Base', 'https://vwo.com/knowledge/', 'VWO', 'design-system-craft', 'evidence-craft', ['ab-testing', 'insights', 'deploy']],
  ['LaunchDarkly Docs', 'https://docs.launchdarkly.com/', 'LaunchDarkly', 'design-system-craft', 'evidence-craft', ['flags', 'segments', 'workflows']],
  ['Split Docs', 'https://docs.split.io/', 'Split', 'design-system-craft', 'evidence-craft', ['feature-flags', 'metrics', 'monitoring']],
  ['Statsig Docs', 'https://docs.statsig.com/', 'Statsig', 'design-system-craft', 'evidence-craft', ['experiments', 'gates', 'warehouse']],
  ['Chameleon Help', 'https://help.chameleon.io/en/', 'Chameleon', 'design-system-craft', 'evidence-craft', ['product-tours', 'surveys', 'launchers']],
  ['Pendo Resource Center', 'https://support.pendo.io/hc/en-us', 'Pendo', 'design-system-craft', 'evidence-craft', ['guides', 'analytics', 'feedback']],
  ['WalkMe Support', 'https://support.walkme.com/', 'WalkMe', 'design-system-craft', 'evidence-craft', ['digital-adoption', 'guidance', 'insights']],
  ['Gainsight PX Docs', 'https://support.gainsight.com/gainsight_px', 'Gainsight PX', 'design-system-craft', 'evidence-craft', ['onboarding', 'engagement', 'analytics']],
  ['Whatfix Support', 'https://support.whatfix.com/', 'Whatfix', 'design-system-craft', 'evidence-craft', ['flows', 'self-help', 'analytics']],
  ['UserTesting Help', 'https://support.usertesting.com/hc/en-us', 'UserTesting', 'design-system-craft', 'evidence-craft', ['tests', 'panels', 'insights']],
  ['UserZoom Help', 'https://help.usertesting.com/hc/en-us', 'UserZoom', 'design-system-craft', 'evidence-craft', ['studies', 'participants', 'reports']],
  ['Lookback Help', 'https://help.lookback.io/', 'Lookback', 'design-system-craft', 'evidence-craft', ['interviews', 'mobile', 'highlights']],
  ['Dovetail Help', 'https://help.dovetail.com/', 'Dovetail', 'design-system-craft', 'evidence-craft', ['research-repo', 'tags', 'insights']],
];
