
export default [
  ['WhatsApp Android Chats', 'https://support.google.com/android/answer/9079661', 'WhatsApp', 'authenticated-home', 'adjacent-domain', 'native-mobile', ['chat-list', 'thread', 'call'], 'flow'],
  ['Signal Android Privacy', 'https://support.signal.org/hc/en-us/categories/360002672331-Android', 'Signal', 'admin-settings', 'adjacent-domain', 'native-mobile', ['privacy', 'notifications', 'linked-devices'], 'flow'],
  ['Telegram Android Channels', 'https://telegram.org/faq#q-what-39s-a-telegram-channel', 'Telegram', 'library-launcher', 'adjacent-domain', 'native-mobile', ['channel-list', 'post', 'subscribe'], 'flow'],
  ['Messenger Android Rooms', 'https://www.facebook.com/help/messenger-app', 'Messenger', 'realtime-multiplayer', 'adjacent-domain', 'native-mobile', ['inbox', 'room', 'video'], 'flow'],
  ['Snapchat Android Memories', 'https://help.snapchat.com/hc/en-us/categories/115000370063-Android', 'Snapchat', 'library-launcher', 'outside-domain', 'native-mobile', ['camera', 'memories', 'story'], 'flow'],
  ['LinkedIn Android Feed', 'https://www.linkedin.com/help/linkedin/answer/a1339728', 'LinkedIn', 'authenticated-home', 'outside-domain', 'native-mobile', ['feed', 'post', 'notifications'], 'flow'],
  ['X Android Communities', 'https://help.x.com/en/using-x/x-for-android', 'X', 'library-launcher', 'outside-domain', 'native-mobile', ['timeline', 'community', 'spaces'], 'flow'],
  ['Bluesky Android Moderation', 'https://blueskyweb.xyz/blog/3-jbnos4om2c2', 'Bluesky', 'admin-settings', 'outside-domain', 'native-mobile', ['feed', 'moderation', 'lists'], 'flow'],
  ['Mastodon Android Timelines', 'https://docs.joinmastodon.org/user/moderation/', 'Mastodon', 'authenticated-home', 'outside-domain', 'native-mobile', ['home', 'local', 'filters'], 'flow'],
  ['Discord Android Server', 'https://support.discord.com/hc/en-us/categories/115000488755-Android', 'Discord', 'operator-control', 'direct-domain', 'native-mobile', ['server-list', 'channel', 'voice'], 'flow'],
  ['Twitch Android Broadcast', 'https://help.twitch.tv/s/article/broadcasting-from-mobile', 'Twitch', 'creation-setup', 'direct-domain', 'native-mobile', ['go-live', 'chat', 'clips'], 'flow'],
  ['YouTube Android Studio', 'https://support.google.com/youtube/answer/2853702', 'YouTube', 'operator-control', 'direct-domain', 'native-mobile', ['studio', 'analytics', 'live'], 'flow'],
  ['OBS Android Guide', 'https://obsproject.com/kb/category/mobile', 'OBS', 'creation-setup', 'direct-domain', 'native-mobile', ['scene', 'stream', 'settings'], 'flow'],
  ['Streamlabs Android', 'https://streamlabs.com/content-hub/post/streamlabs-mobile-app', 'Streamlabs', 'creation-setup', 'direct-domain', 'native-mobile', ['alert', 'stream', 'multistream'], 'flow'],
  ['Samsung SmartThings Android', 'https://www.samsung.com/us/support/answer/ANS10002559/', 'Samsung', 'admin-settings', 'adjacent-domain', 'native-mobile', ['devices', 'automations', 'rooms'], 'flow'],
  ['Netflix Android Downloads', 'https://help.netflix.com/en/node/54816', 'Netflix', 'library-launcher', 'outside-domain', 'native-mobile', ['browse', 'download', 'profile'], 'flow'],
  ['Disney+ Android GroupWatch', 'https://help.disneyplus.com/csp', 'Disney+', 'realtime-multiplayer', 'outside-domain', 'native-mobile', ['home', 'groupwatch', 'profile'], 'flow'],
  ['Prime Video Android X-Ray', 'https://www.amazon.com/gp/help/customer/display.html?nodeId=G9SY6AQPM755DKP2', 'Amazon Prime Video', 'authenticated-home', 'outside-domain', 'native-mobile', ['browse', 'x-ray', 'download'], 'flow'],
  ['Uber Android Trip', 'https://help.uber.com/riders/article/how-to-request-a-ride', 'Uber', 'commerce-checkout', 'outside-domain', 'native-mobile', ['map', 'trip', 'receipt'], 'flow'],
  ['Lyft Android Ride', 'https://help.lyft.com/hc/en-us/categories/200794158-Rider', 'Lyft', 'commerce-checkout', 'outside-domain', 'native-mobile', ['pickup', 'ride', 'payment'], 'flow'],
  ['DoorDash Android Order', 'https://help.doordash.com/consumers/s/article/How-do-I-place-an-order', 'DoorDash', 'commerce-checkout', 'outside-domain', 'native-mobile', ['browse', 'cart', 'track'], 'flow'],
  ['Airbnb Android Trips', 'https://www.airbnb.com/help/article/89/how-do-i-book-a-place-to-stay', 'Airbnb', 'commerce-checkout', 'outside-domain', 'native-mobile', ['search', 'book', 'trips'], 'flow'],
  ['Samsung Galaxy Tips', 'https://www.samsung.com/us/support/mobile/phones/', 'Samsung', 'admin-settings', 'outside-domain', 'native-mobile', ['settings', 'tips', 'device-care'], 'flow'],
  ['Google Pixel Features', 'https://support.google.com/pixelphone', 'Google Pixel', 'admin-settings', 'outside-domain', 'native-mobile', ['settings', 'features', 'safety'], 'flow'],
  ['OnePlus OxygenOS Guide', 'https://www.oneplus.com/support/softwareupgrade', 'OnePlus', 'admin-settings', 'outside-domain', 'native-mobile', ['settings', 'customization', 'gestures'], 'flow'],
];
