
export default [
  ['Kick Creator Dashboard', 'https://help.kick.com/en/articles/kick-creator-tools', 'Kick', 'operator-control', 'direct-domain', ['dashboard', 'analytics', 'monetization']],
  ['Rumble Creator Studio', 'https://rumble.com/help/creator-studio', 'Rumble', 'operator-control', 'direct-domain', ['upload', 'analytics', 'monetization']],
  ['Trovo Creator Portal', 'https://help.trovo.live/creator-portal', 'Trovo', 'operator-control', 'direct-domain', ['dashboard', 'quests', 'rewards']],
  ['DLive Streamer Dashboard', 'https://help.dlive.tv/streamer-dashboard', 'DLive', 'operator-control', 'direct-domain', ['dashboard', 'rewards', 'settings']],
  ['Caffeine Creator Hub', 'https://help.caffeine.tv/creator-hub', 'Caffeine', 'operator-control', 'direct-domain', ['hub', 'broadcast', 'community']],
  ['Picarto Streamer Settings', 'https://help.picarto.tv/streamer-settings', 'Picarto', 'operator-control', 'direct-domain', ['settings', 'categories', 'alerts']],
  ['Steam Broadcast Setup', 'https://help.steampowered.com/en/wizard/HelpWithBroadcasting', 'Steam', 'creation-setup', 'direct-domain', ['setup', 'settings', 'go-live']],
  ['Epic Games Creator Portal', 'https://dev.epicgames.com/documentation/en-us/fortnite/creator-portal', 'Epic Games', 'creation-setup', 'direct-domain', ['portal', 'island', 'publish']],
  ['EA App Cloud Saves', 'https://help.ea.com/en/help/ea/ea-app/cloud-saves/', 'EA', 'authenticated-home', 'direct-domain', ['library', 'cloud', 'sync']],
  ['GOG Galaxy Library', 'https://support.gog.com/hc/en-us/articles/galaxy-library', 'GOG', 'library-launcher', 'direct-domain', ['library', 'friends', 'overlay']],
  ['Battle.net App Settings', 'https://us.battle.net/support/en/article/battlenet-app-settings', 'Battle.net', 'admin-settings', 'direct-domain', ['settings', 'voice', 'downloads']],
  ['Ubisoft Connect Rewards', 'https://help.ubisoft.com/ubisoft-connect-rewards', 'Ubisoft', 'authenticated-home', 'direct-domain', ['rewards', 'challenges', 'profile']],
  ['PlayStation Remote Play Setup', 'https://www.playstation.com/en-us/support/games/playstation-remote-play-on-pc-and-mac/', 'PlayStation', 'creation-setup', 'adjacent-domain', ['setup', 'pair', 'stream']],
  ['Xbox Remote Play Guide', 'https://support.xbox.com/en-US/help/games-apps/game-setup-and-play/remote-play', 'Xbox', 'creation-setup', 'adjacent-domain', ['setup', 'console', 'stream']],
  ['Nintendo Switch Online App', 'https://en-americas-support.nintendo.com/app/switch/nintendo_switch_online_app', 'Nintendo', 'authenticated-home', 'adjacent-domain', ['app', 'voice', 'games']],
  ['GeForce NOW Settings', 'https://www.nvidia.com/en-us/geforce-now/system-req/', 'GeForce NOW', 'admin-settings', 'adjacent-domain', ['settings', 'quality', 'session']],
  ['Parsec Host Settings', 'https://support.parsec.app/hc/en-us/articles/host-settings', 'Parsec', 'admin-settings', 'direct-domain', ['host', 'permissions', 'quality']],
  ['Moonlight PC Setup', 'https://moonlight-stream.org/setup/', 'Moonlight', 'creation-setup', 'outside-domain', ['setup', 'pair', 'stream']],
  ['Rainway Host Dashboard', 'https://docs.rainway.com/docs/host-dashboard', 'Rainway', 'operator-control', 'outside-domain', ['host', 'dashboard', 'settings']],
  ['NVIDIA Broadcast Setup', 'https://www.nvidia.com/en-us/geforce/broadcasting/broadcast-app/', 'NVIDIA Broadcast', 'creation-setup', 'direct-domain', ['setup', 'effects', 'camera']],
  ['Elgato Wave Link Mixing', 'https://help.elgato.com/hc/en-us/articles/wave-link-mixing', 'Elgato', 'operator-control', 'direct-domain', ['mixing', 'monitor', 'output']],
  ['Audacity Multi Track', 'https://manual.audacityteam.org/man/multi_track_overdubbing.html', 'Audacity', 'creation-setup', 'outside-domain', ['tracks', 'record', 'export']],
  ['REAPER Routing Guide', 'https://www.reaper.fm/userguide.php', 'REAPER', 'creation-setup', 'outside-domain', ['routing', 'tracks', 'render']],
  ['Voicemeeter Banana Setup', 'https://vb-audio.com/Voicemeeter/banana.htm', 'Voicemeeter', 'creation-setup', 'outside-domain', ['inputs', 'bus', 'output']],
  ['Open Broadcaster NDI Output', 'https://obsproject.com/kb/ndi-output', 'OBS', 'creation-setup', 'direct-domain', ['ndi', 'output', 'settings']],
];
