export default [
  ['Linear Changelog Page', 'https://linear.app/changelog', 'Linear', 'editorial-experimental', 'outside-domain', ['changelog', 'release-notes', 'subscribe'], 'flow'],
  ['Vercel Changelog', 'https://vercel.com/changelog', 'Vercel', 'editorial-experimental', 'outside-domain', ['changelog', 'product-updates', 'filter'], 'flow'],
  ['Stripe Changelog', 'https://stripe.com/blog/changelog', 'Stripe', 'editorial-experimental', 'outside-domain', ['changelog', 'api-changes', 'subscribe'], 'flow'],
  ['GitHub Changelog', 'https://github.blog/changelog/', 'GitHub', 'editorial-experimental', 'outside-domain', ['changelog', 'feature-flags', 'enterprise'], 'flow'],
  ['Figma Release Notes', 'https://www.figma.com/release-notes/', 'Figma', 'editorial-experimental', 'direct-domain', ['release-notes', 'features', 'fixes'], 'flow'],
  ['Notion Release Notes', 'https://www.notion.so/releases', 'Notion', 'editorial-experimental', 'direct-domain', ['releases', 'features', 'templates'], 'flow'],
  ['Slack Release Notes', 'https://slack.com/release-notes', 'Slack', 'editorial-experimental', 'adjacent-domain', ['release-notes', 'desktop', 'mobile'], 'flow'],
  ['Discord Blog Updates', 'https://discord.com/blog', 'Discord', 'editorial-experimental', 'adjacent-domain', ['blog', 'product-updates', 'community'], 'flow'],
  ['Twitch Blog Creator', 'https://blog.twitch.tv/', 'Twitch', 'editorial-experimental', 'direct-domain', ['blog', 'creator-tools', 'policy'], 'flow'],
  ['YouTube Creator Blog', 'https://blog.youtube/', 'YouTube', 'editorial-experimental', 'adjacent-domain', ['blog', 'monetization', 'features'], 'flow'],
  ['Spotify for Artists News', 'https://artists.spotify.com/en/news', 'Spotify', 'editorial-experimental', 'adjacent-domain', ['news', 'analytics', 'promotion'], 'flow'],
  ['Apple Newsroom Design', 'https://www.apple.com/newsroom/', 'Apple', 'editorial-experimental', 'outside-domain', ['newsroom', 'product-launch', 'press'], 'flow'],
  ['Google Design Blog', 'https://design.google/library/', 'Google', 'editorial-experimental', 'evidence-craft', ['library', 'case-study', 'motion'], 'case-study'],
  ['Microsoft Design Blog', 'https://www.microsoft.com/design/blog/', 'Microsoft', 'editorial-experimental', 'outside-domain', ['blog', 'fluent', 'inclusive'], 'flow'],
  ['Airbnb Design Blog', 'https://airbnb.design/', 'Airbnb', 'editorial-experimental', 'outside-domain', ['blog', 'research', 'brand'], 'case-study'],
  ['Dropbox Design Blog', 'https://dropbox.design/', 'Dropbox', 'editorial-experimental', 'outside-domain', ['blog', 'systems', 'culture'], 'case-study'],
  ['Intercom Blog Product', 'https://www.intercom.com/blog/product/', 'Intercom', 'editorial-experimental', 'outside-domain', ['blog', 'messenger', 'ai'], 'flow'],
  ['Basecamp Shape Up', 'https://basecamp.com/shapeup', 'Basecamp', 'editorial-experimental', 'evidence-craft', ['methodology', 'betting-table', 'cool-down'], 'case-study'],
  ['First Round Review Design', 'https://review.firstround.com/design/', 'First Round', 'editorial-experimental', 'evidence-craft', ['articles', 'startup', 'product'], 'case-study'],
  ['Lenny Newsletter Archive', 'https://www.lennysnewsletter.com/archive', 'Lenny', 'editorial-experimental', 'evidence-craft', ['archive', 'product', 'growth'], 'case-study'],
  ['Stratechery Design Posts', 'https://stratechery.com/category/daily-email/', 'Stratechery', 'editorial-experimental', 'outside-domain', ['analysis', 'platform', 'strategy'], 'case-study'],
  ['A16z Consumer Design', 'https://a16z.com/category/consumer/', 'a16z', 'editorial-experimental', 'outside-domain', ['consumer', 'trends', 'design'], 'case-study'],
  ['Product Hunt Launch Page', 'https://www.producthunt.com/', 'Product Hunt', 'editorial-experimental', 'outside-domain', ['launch', 'upvote', 'comment'], 'flow'],
  ['Indie Hackers Stories', 'https://www.indiehackers.com/', 'Indie Hackers', 'editorial-experimental', 'outside-domain', ['stories', 'revenue', 'build-in-public'], 'flow'],
  ['Hacker News Show HN Patterns', 'https://news.ycombinator.com/show', 'Hacker News', 'editorial-experimental', 'outside-domain', ['show', 'launch', 'feedback'], 'flow'],
];
