export default [
  ['MeasuringU Blog', 'https://measuringu.com/blog/', 'MeasuringU', 'design-system-craft', 'evidence-craft', ['metrics', 'methods', 'articles'], 'case-study'],
  ['UXmatters Archives', 'https://www.uxmatters.com/', 'UXmatters', 'editorial-experimental', 'evidence-craft', ['topics', 'articles', 'archive'], 'case-study'],
  ['Boxes and Arrows', 'https://boxesandarrows.com/', 'Boxes and Arrows', 'editorial-experimental', 'evidence-craft', ['essays', 'patterns', 'archive'], 'case-study'],
  ['IxDF Literature Topics', 'https://www.interaction-design.org/literature/topics', 'Interaction Design Foundation', 'library-launcher', 'evidence-craft', ['topics', 'articles', 'courses'], 'guideline'],
  ['Cooper Journal', 'https://www.cooper.com/journal', 'Cooper', 'editorial-experimental', 'evidence-craft', ['posts', 'methods', 'archive'], 'case-study'],
  ['Design Google Library', 'https://design.google/library', 'Google Design', 'library-launcher', 'evidence-craft', ['library', 'articles', 'topics'], 'design-system'],
  ['Microsoft Design Articles', 'https://microsoft.design/articles/', 'Microsoft Design', 'editorial-experimental', 'evidence-craft', ['articles', 'systems', 'culture'], 'case-study'],
  ['Spotify Design Articles', 'https://spotify.design/articles', 'Spotify Design', 'editorial-experimental', 'evidence-craft', ['articles', 'research', 'systems'], 'case-study'],
  ['Slack Design Articles', 'https://slack.design/articles/', 'Slack Design', 'editorial-experimental', 'evidence-craft', ['articles', 'patterns', 'brand'], 'case-study'],
  ['GOV.UK User Research Manual', 'https://www.gov.uk/service-manual/user-research', 'GOV.UK', 'creation-setup', 'evidence-craft', ['plan', 'recruit', 'synthesize'], 'guideline'],
  ['Usability.gov User-Centered Design', 'https://www.usability.gov/what-and-why/user-centered-design.html', 'Usability.gov', 'design-system-craft', 'evidence-craft', ['ucd', 'process', 'methods'], 'guideline'],
  ['WebAIM Articles', 'https://webaim.org/articles/', 'WebAIM', 'design-system-craft', 'evidence-craft', ['a11y', 'articles', 'guides'], 'guideline'],
  ['CX Partners Thinking', 'https://cxpartners.co.uk/thinking/', 'CX Partners', 'editorial-experimental', 'evidence-craft', ['insights', 'cases', 'methods'], 'case-study'],
  ['Userfocus Articles', 'https://www.userfocus.co.uk/articles/', 'Userfocus', 'library-launcher', 'evidence-craft', ['articles', 'methods', 'tools'], 'case-study'],
  ['UX Booth Articles', 'https://www.uxbooth.com/articles/', 'UX Booth', 'editorial-experimental', 'evidence-craft', ['articles', 'patterns', 'archive'], 'case-study'],
  ['Mule Design Blog', 'https://muledesign.com/blog/', 'Mule Design', 'editorial-experimental', 'evidence-craft', ['posts', 'process', 'culture'], 'case-study'],
  ['Adobe UX Blog', 'https://blog.adobe.com/en/topics/creativity/design/ux-design', 'Adobe', 'design-system-craft', 'evidence-craft', ['articles', 'case-study'], 'case-study'],
  ['UX Design Institute Blog', 'https://www.uxdesigninstitute.com/blog/', 'UX Design Institute', 'editorial-experimental', 'evidence-craft', ['articles', 'career', 'methods'], 'case-study'],
  ['Hotjar Blog UX', 'https://www.hotjar.com/blog/ux/', 'Hotjar', 'editorial-experimental', 'evidence-craft', ['articles', 'research', 'tools'], 'case-study'],
  ['Optimizely Blog', 'https://www.optimizely.com/insights/blog/', 'Optimizely', 'editorial-experimental', 'evidence-craft', ['experimentation', 'articles'], 'case-study'],
  ['Microsoft Clarity Blog', 'https://clarity.microsoft.com/blog/', 'Microsoft Clarity', 'operator-control', 'evidence-craft', ['analytics', 'heatmaps', 'insights'], 'case-study'],
  ['Content Design London Blog', 'https://contentdesign.london/blog/', 'Content Design London', 'editorial-experimental', 'evidence-craft', ['content', 'plain-language'], 'case-study'],
  ['Service Design Network Blog', 'https://www.service-design-network.org/blog', 'Service Design Network', 'editorial-experimental', 'evidence-craft', ['service-design', 'cases'], 'case-study'],
  ['NN Progressive Disclosure', 'https://www.nngroup.com/articles/progressive-disclosure/', 'Nielsen Norman Group', 'design-system-craft', 'evidence-craft', ['pattern', 'navigation', 'detail'], 'guideline'],
  ['NN Ten Usability Heuristics', 'https://www.nngroup.com/articles/ten-usability-heuristics/', 'Nielsen Norman Group', 'design-system-craft', 'evidence-craft', ['heuristics', 'evaluation'], 'guideline'],
  ['NN Error Message Guidelines', 'https://www.nngroup.com/articles/error-message-guidelines/', 'Nielsen Norman Group', 'design-system-craft', 'evidence-craft', ['errors', 'microcopy'], 'guideline'],
  ['NN Microcopy UX Writing', 'https://www.nngroup.com/articles/microcopy-ux-writing/', 'Nielsen Norman Group', 'design-system-craft', 'evidence-craft', ['microcopy', 'labels'], 'guideline'],
  ['IBM Design Thinking Practice', 'https://www.ibm.com/design/thinking/', 'IBM', 'creation-setup', 'evidence-craft', ['framework', 'workshop', 'sprint'], 'guideline'],
  ['Deque Blog Accessibility', 'https://www.deque.com/blog/', 'Deque', 'design-system-craft', 'evidence-craft', ['a11y', 'articles', 'testing'], 'guideline'],
  ['InVision Design Blog Archive', 'https://www.invisionapp.com/inside-design', 'InVision', 'editorial-experimental', 'evidence-craft', ['design', 'collaboration'], 'case-study'],
  ['iOS NameDrop Contact Poster', 'https://support.apple.com/guide/iphone/use-namedrop-to-share-contact-info-iph4a4a94627/ios', 'Apple', 'auth-onboarding', 'adjacent-domain', 'native-mobile', ['namedrop', 'share', 'contact'], 'guideline'],
  ['Android Picture-in-Picture', 'https://support.google.com/android/answer/9455138', 'Google', 'operator-control', 'adjacent-domain', 'native-mobile', ['pip', 'multitask', 'video'], 'guideline'],
  ['Android Circle to Search', 'https://support.google.com/pixelphone/answer/14101169', 'Google', 'library-launcher', 'adjacent-domain', 'native-mobile', ['search', 'gesture', 'overlay'], 'guideline'],
  ['iOS Live Voicemail Transcript', 'https://support.apple.com/guide/iphone/view-a-live-voicemail-transcription-iphfedc4930/ios', 'Apple', 'operator-control', 'adjacent-domain', 'native-mobile', ['voicemail', 'transcript', 'call'], 'guideline'],
  ['Samsung Galaxy Multi Window', 'https://www.samsung.com/us/support/answer/ANS00062033/', 'Samsung', 'operator-control', 'adjacent-domain', 'native-mobile', ['split-screen', 'multitask'], 'guideline'],
  ['Android Nearby Share Quick', 'https://support.google.com/android/answer/15728569', 'Google', 'auth-onboarding', 'adjacent-domain', 'native-mobile', ['nearby', 'share', 'files'], 'guideline'],
  ['iOS Journal App Entries', 'https://support.apple.com/guide/iphone/create-journal-entries-iph0c29aeada/ios', 'Apple', 'creation-setup', 'adjacent-domain', 'native-mobile', ['journal', 'reflect', 'entries'], 'guideline'],
];
